In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

# LOAD RAW MAFS

In [2]:
pd.set_option('display.max_columns', None)

folder = '/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/mafs'
files = sorted(os.listdir(folder))
germline_dfs = []
for f in files:
    print(f)
    if not f.endswith('.maf'):
        continue
    d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
    #display(d)
    sample = f.replace('_HaplotypeCaller.maf', '')
    d['sample'] = sample
    germline_dfs.append(d)

germline = pd.concat(germline_dfs).dropna(axis=1, how='all')
display(germline)

BIDMC1_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC2_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC3_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC4_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC5_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC6_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC7_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC8_B_HaplotypeCaller.maf
DFC10_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC11_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC12_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC13_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC14_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC15_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC16_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC17_B_HaplotypeCaller.maf
DFC19_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC1_B_HaplotypeCaller.maf
DFC20_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC23_B_HaplotypeCaller.maf
DFC2_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC4_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC6_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC7_B_HaplotypeCaller.maf
DFC8_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC9_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH10_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH11_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH12_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH13_B_HaplotypeCaller.maf
MGH2_B_HaplotypeCaller.maf
MGH3_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH4_B_HaplotypeCaller.maf
MGH5_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH6_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH7_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH8_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH9_B_HaplotypeCaller.maf
MGNS2_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGNS4_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGNS5_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGNS6_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

NWH1_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

NWH2_B_HaplotypeCaller.maf
NWH3_B_HaplotypeCaller.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/3529033056.py:10: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,t_depth,t_ref_count,t_alt_count,FILTER,flanking_bps,vcf_id,vcf_qual,vcf_pos,sample
0,Unknown,0,.,GRCh38,1,69270,69270,+,Targeted_Region,SNP,A,G,G,BIDMC1_B,NORMAL,A,A,14,0,14,.,CAC,.,383.77,69270,BIDMC1_B
1,Unknown,0,.,GRCh38,1,69511,69511,+,Targeted_Region,SNP,A,G,G,BIDMC1_B,NORMAL,A,A,263,0,263,.,CAC,.,6929.77,69511,BIDMC1_B
2,Unknown,0,.,GRCh38,1,69897,69897,+,Targeted_Region,SNP,T,C,C,BIDMC1_B,NORMAL,T,T,10,0,10,.,CTG,.,268.77,69897,BIDMC1_B
3,Unknown,0,.,GRCh38,1,930939,930939,+,Targeted_Region,SNP,G,A,A,BIDMC1_B,NORMAL,G,G,92,0,92,.,CGG,.,3022.77,930939,BIDMC1_B
4,Unknown,0,.,GRCh38,1,931131,931132,+,Targeted_Region,INS,-,-,CCCT,BIDMC1_B,NORMAL,-,-,122,64,58,.,TCC,.,2125.73,931131,BIDMC1_B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79214,Unknown,0,.,GRCh38,MT,15326,15326,+,Targeted_Region,SNP,A,G,G,NWH3_B,NORMAL,A,A,6753,8,6745,.,AAC,.,270119.77,15326,NWH3_B
79215,Unknown,0,.,GRCh38,MT,16189,16189,+,Targeted_Region,SNP,T,C,C,NWH3_B,NORMAL,T,T,5573,178,5395,.,CTC,.,164216.77,16189,NWH3_B
79216,Unknown,0,.,GRCh38,MT,16192,16192,+,Targeted_Region,SNP,C,T,T,NWH3_B,NORMAL,C,C,5811,55,5756,.,CCC,.,205945.73,16192,NWH3_B
79217,Unknown,0,.,GRCh38,MT,16270,16270,+,Targeted_Region,SNP,C,T,T,NWH3_B,NORMAL,C,C,6432,6,6426,.,ACT,.,241684.77,16270,NWH3_B
79218,Unknown,0,.,GRCh38,MT,16398,16398,+,Targeted_Region,SNP,G,A,A,NWH3_B,NORMAL,G,G,6868,0,6868,.,TGA,.,257254.77,16398,NWH3_B

# PREP DATA FOR ANNOVAR

In [3]:
mandatory = ['Chromosome','Start_Position', 'End_Position','Reference_Allele', 'Tumor_Seq_Allele2']
optional = ['Tumor_Sample_Barcode', 't_depth', 't_ref_count', 't_alt_count', 'FILTER']
print(mandatory  + optional)
new = germline.loc[:, mandatory  + optional]
new

['Chromosome', 'Start_Position', 'End_Position', 'Reference_Allele', 'Tumor_Seq_Allele2', 'Tumor_Sample_Barcode', 't_depth', 't_ref_count', 't_alt_count', 'FILTER']

,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,t_depth,t_ref_count,t_alt_count,FILTER
0,1,69270,69270,A,G,BIDMC1_B,14,0,14,.
1,1,69511,69511,A,G,BIDMC1_B,263,0,263,.
2,1,69897,69897,T,C,BIDMC1_B,10,0,10,.
3,1,930939,930939,G,A,BIDMC1_B,92,0,92,.
4,1,931131,931132,-,CCCT,BIDMC1_B,122,64,58,.
...,...,...,...,...,...,...,...,...,...,...
79214,MT,15326,15326,A,G,NWH3_B,6753,8,6745,.
79215,MT,16189,16189,T,C,NWH3_B,5573,178,5395,.
79216,MT,16192,16192,C,T,NWH3_B,5811,55,5756,.
79217,MT,16270,16270,C,T,NWH3_B,6432,6,6426,.
79218,MT,16398,16398,G,A,NWH3_B,6868,0,6868,.

In [4]:
path = '/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_pre_annovar.csv' 
new.to_csv(path, sep = '\t', index=False, header=False)

# RUN ANNOVAR

In [5]:
#cmd = f'cd /Users/jacobg/CNN/annovar && perl table_annovar.pl {path} --protocol refGene --operation gx, humandb/ -buildver hg38 -out {path.replace("_pre", "")} -xref example/gene_fullxref.txt --remove --otherinfo'
cmd = f'cd /Users/jacobg/CNN/annovar && perl table_annovar.pl {path} --protocol refGene,clinvar_20210123  --operation gx,f humandb/ -buildver hg38 -out {path.replace("_pre", "")} -xref example/gene_fullxref.txt --remove --otherinfo'
os.system(cmd)

NOTICE: the --polish argument is set ON automatically (use --nopolish to change this behavior)
-----------------------------------------------------------------
NOTICE: Processing operation=gx protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene -exonsort -nofirstcodondel /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_pre_annovar.csv humandb/>
NOTICE: Output files are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.variant_function, /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.exonic_variant_function
NOTICE: Reading gene annotation from humandb/hg38_refGene.txt ... Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 3363296 unique variants in 3363296 input lines
NOTICE: Finished analyzing 1000000 query variants
NOTICE: Finished analyzing 2000000 query variants
NOTICE: Finished analyzing 3000000 query variants
NOTICE: Reading FASTA sequences from humandb/hg38_refGeneMrna.fa ... Done with 51513 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
NOTICE: Variants with invalid input format are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.invalid_input

NOTICE: Running with system command <coding_change.pl  /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.exonic_variant_function.orig humandb//hg38_refGene.txt humandb//hg38_refGeneMrna.fa -alltranscript -out /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.fa -newevf /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.refGene.exonic_variant_function>
Warning: 27 transcripts are flagged as having potential ORF issues (premature stopcodon or lack of stop codon)
NOTICE: The xrefkey is provided in header as <pLi pRec pNull Gene_full_name Function_description Disease_description Tissue_specificity(Uniprot) Expression(egenetics) Expression(GNF/Atlas) P(HI) P(rec) RVIS RVIS_percentile GDI GDI-Phred>
NOTICE: Finished reading 597255 cross references (each with 15 fields) from example/gene_fullxref.txt
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20210123
NOTICE: Finished reading 5 column headers for '-dbtype clinvar_20210123'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20210123 -buildver hg38 -outfile /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_pre_annovar.csv humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20210123 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.hg38_clinvar_20210123_dropped, and output file with other variants is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.hg38_clinvar_20210123_filtered
NOTICE: Processing next batch with 307210 unique variants in 3603441 input lines
NOTICE: Database index loaded. Total number of bins is 75012 and the number of bins to be scanned is 49850
NOTICE: Scanning filter database humandb/hg38_clinvar_20210123.txt...Done
NOTICE: Variants with invalid input format are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.invalid_input
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.hg38_multianno.txt

0

# REFORMATTING

In [6]:
annovar_path='/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/germline/data/combined/combined_germline_mutations_annovar.csv.hg38_multianno.txt'
results = pd.read_csv(annovar_path, sep='\t')
results = results.rename(columns={'Otherinfo1': 'Tumor_Sample_Barcode',
                                  'Otherinfo2': 't_depth',   
                                  'Otherinfo3': 't_ref_count',
                                  'Otherinfo4': 't_alt_count',
                                  'Otherinfo5': 'FILTER'})
display(results)
results.to_csv(annovar_path, sep='\t', index=False)

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_74752/1682622166.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv(annovar_path, sep='\t')

,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,AAChange.refGene,pLi.refGene,pRec.refGene,pNull.refGene,Gene_full_name.refGene,Function_description.refGene,Disease_description.refGene,Tissue_specificity(Uniprot).refGene,Expression(egenetics).refGene,Expression(GNF/Atlas).refGene,P(HI).refGene,P(rec).refGene,RVIS.refGene,RVIS_percentile.refGene,GDI.refGene,GDI-Phred.refGene,CLNALLELEID,CLNDN,CLNDISDB,CLNREVSTAT,CLNSIG,Tumor_Sample_Barcode,t_depth,t_ref_count,t_alt_count,FILTER
0,1,69270,69270,A,G,exonic,OR4F5,NaN,synonymous SNV,OR4F5:NM_001005484:exon1:c.A180G:p.S60S,0.176329298172162,0.644086264144236,0.179584437683602,olfactory receptor family 4 subfamily F member 5,FUNCTION: Odorant receptor. {ECO:0000305}.;,.,.,.,.,0.06092,0.07159,.,.,113.16669,2.31572,NaN,NaN,NaN,NaN,NaN,BIDMC1_B,14,0,14,.
1,1,69511,69511,A,G,exonic,OR4F5,NaN,nonsynonymous SNV,OR4F5:NM_001005484:exon1:c.A421G:p.T141A,0.176329298172162,0.644086264144236,0.179584437683602,olfactory receptor family 4 subfamily F member 5,FUNCTION: Odorant receptor. {ECO:0000305}.;,.,.,.,.,0.06092,0.07159,.,.,113.16669,2.31572,NaN,NaN,NaN,NaN,NaN,BIDMC1_B,263,0,263,.
2,1,69897,69897,T,C,exonic,OR4F5,NaN,synonymous SNV,OR4F5:NM_001005484:exon1:c.T807C:p.S269S,0.176329298172162,0.644086264144236,0.179584437683602,olfactory receptor family 4 subfamily F member 5,FUNCTION: Odorant receptor. {ECO:0000305}.;,.,.,.,.,0.06092,0.07159,.,.,113.16669,2.31572,NaN,NaN,NaN,NaN,NaN,BIDMC1_B,10,0,10,.
3,1,930939,930939,G,A,intronic,SAMD11,NaN,NaN,NaN,1.35381157129201e-10,0.18370000637236,0.816299993492259,sterile alpha motif domain containing 11,FUNCTION: May play a role in photoreceptor dev...,.,.,lymphoreticular;ovary;salivary gland;developme...,.,0.10109,.,.,.,835.24604,5.65821,NaN,NaN,NaN,NaN,NaN,BIDMC1_B,92,0,92,.
4,1,931131,931132,-,CCCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BIDMC1_B,122,64,58,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3603436,MT,15326,15326,A,G,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWH3_B,6753,8,6745,.
3603437,MT,16189,16189,T,C,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWH3_B,5573,178,5395,.
3603438,MT,16192,16192,C,T,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWH3_B,5811,55,5756,.
3603439,MT,16270,16270,C,T,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWH3_B,6432,6,6426,.
3603440,MT,16398,16398,G,A,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NWH3_B,6868,0,6868,.