In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

# ALL TUMOR VARIANTS

In [2]:
pd.set_option('display.max_columns', None)

folder = '/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/filtered/maf'
files = os.listdir(folder)
cols = ['Tumor_Sample_Barcode', 'Chromosome', 'vcf_pos', 'Reference_Allele', 'Tumor_Seq_Allele2']
dfs = []
for f in files:
    print(f)
    if not f.endswith('.maf'):
        continue
    d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
    sample = f.replace('_filtered.MuTect2.maf', '')
    d['sample'] = sample
    dfs.append(d)


df = pd.concat(dfs).dropna(axis=1, how='all')
display(df)

MGNS5_post_filtered.MuTect2.maf
MGNS5_pre_filtered.MuTect2.maf
DFC20_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC17_pre_filtered.MuTect2.maf
DFC13_pre_filtered.MuTect2.maf
BIDMC6_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC15_pre_FFT_filtered.MuTect2.maf
BIDMC2_pre_filtered.MuTect2.maf
BIDMC4_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC12_post_filtered.MuTect2.maf
DFC9_pre_filtered.MuTect2.maf
BIDMC3_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH9_pre_filtered.MuTect2.maf
MGH5_pre_filtered.MuTect2.maf
NWH3_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC1_pre_filtered.MuTect2.maf
MGH11_pre_filtered.MuTect2.maf
MGH8_pre_filtered.MuTect2.maf
DFC23_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH3_post_filtered.MuTect2.maf
MGH10_pre_filtered.MuTect2.maf
MGH11_post_filtered.MuTect2.maf
DFC2_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC6_post_filtered.MuTect2.maf
MGH4_pre_filtered.MuTect2.maf
DFC16_pre_filtered.MuTect2.maf
MGNS4_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC3_pre_filtered.MuTect2.maf
DFC8_pre_FFT_filtered.MuTect2.maf
BIDMC7_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC2_pre_filtered.MuTect2.maf
MGH6_pre_filtered.MuTect2.maf
DFC6_pre_filtered.MuTect2.maf
MGH5_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH2_pre_filtered.MuTect2.maf
MGH12_pre_filtered.MuTect2.maf
DFC7_pre_FFT_filtered.MuTect2.maf
DFC16_post_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC4_post_filtered.MuTect2.maf
DFC4_pre_FFT_filtered.MuTect2.maf
BIDMC5_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

BIDMC7_post_filtered.MuTect2.maf
BIDMC1_pre_filtered.MuTect2.maf
MGNS6_pre_filtered.MuTect2.maf
DFC23_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC14_pre_filtered.MuTect2.maf
MGNS2_pre_filtered.MuTect2.maf
MGNS6_post_filtered.MuTect2.maf
DFC10_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC19_pre_filtered.MuTect2.maf
BIDMC4_pre_filtered.MuTect2.maf
DFC11_pre_filtered.MuTect2.maf
BIDMC8_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

NWH3_post_filtered.MuTect2.maf
NWH2_pre_FFT_filtered.MuTect2.maf
DFC1_post_filtered.MuTect2.maf
MGH13_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

MGH12_post_filtered.MuTect2.maf
MGH3_pre_filtered.MuTect2.maf
BIDMC5_post_filtered.MuTect2.maf
DFC7_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC13_post_filtered.MuTect2.maf
MGH7_pre_filtered.MuTect2.maf
NWH1_pre_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

DFC20_post_filtered.MuTect2.maf
MGNS4_post_filtered.MuTect2.maf
DFC1_pre_FFT_filtered.MuTect2.maf

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')
/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/4046668882.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv(f'{folder}/{f}', header=1, sep='\t')

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,t_depth,t_ref_count,t_alt_count,n_depth,n_ref_count,n_alt_count,FILTER,flanking_bps,vcf_id,vcf_qual,vcf_pos,sample
0,Unknown,0,.,GRCh38,1,942752,942752,+,Targeted_Region,DEL,C,C,-,MGNS5_post,MGNS5_B,C,C,513,508,5,417,414,3,artifact_in_normal;t_lod,GACC,.,.,942751,MGNS5_post
1,Unknown,0,.,GRCh38,1,956853,956853,+,Targeted_Region,SNP,C,C,A,MGNS5_post,MGNS5_B,C,C,166,159,7,103,103,0,PASS,TCT,.,.,956853,MGNS5_post
2,Unknown,0,.,GRCh38,1,957251,957251,+,Targeted_Region,SNP,C,C,G,MGNS5_post,MGNS5_B,C,C,481,466,15,241,241,0,PASS,TCA,.,.,957251,MGNS5_post
3,Unknown,0,.,GRCh38,1,963297,963297,+,Targeted_Region,SNP,G,G,A,MGNS5_post,MGNS5_B,G,G,238,234,4,290,290,0,t_lod,CGC,.,.,963297,MGNS5_post
4,Unknown,0,.,GRCh38,1,973283,973283,+,Targeted_Region,SNP,A,A,G,MGNS5_post,MGNS5_B,A,A,380,377,3,343,343,0,t_lod,GAG,.,.,973283,MGNS5_post
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24643,Unknown,0,.,GRCh38,MT,12990,12992,+,Targeted_Region,DEL,AGC,AGC,-,DFC1_pre_FFT,DFC1_B,AGC,AGC,4367,4355,12,1544,1540,4,artifact_in_normal;str_contraction,CTAGCA,.,.,12989,DFC1_pre_FFT
24644,Unknown,0,.,GRCh38,MT,13762,13762,+,Targeted_Region,SNP,T,T,G,DFC1_pre_FFT,DFC1_B,T,T,3525,3466,59,1275,1260,15,artifact_in_normal;base_quality,ATC,.,.,13762,DFC1_pre_FFT
24645,Unknown,0,.,GRCh38,MT,14808,14808,+,Targeted_Region,SNP,T,T,C,DFC1_pre_FFT,DFC1_B,T,T,4514,4507,7,1841,1841,0,t_lod,CTC,.,.,14808,DFC1_pre_FFT
24646,Unknown,0,.,GRCh38,MT,14831,14831,+,Targeted_Region,SNP,G,G,A,DFC1_pre_FFT,DFC1_B,G,G,4606,4598,8,1849,1848,1,t_lod,CGC,.,.,14831,DFC1_pre_FFT
24647,Unknown,0,.,GRCh38,MT,16390,16390,+,Targeted_Region,SNP,G,G,A,DFC1_pre_FFT,DFC1_B,G,G,4843,4828,15,1745,1735,10,artifact_in_normal,GGG,.,.,16390,DFC1_pre_FFT

In [3]:
df.to_csv('/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_raw.csv', index=False)

In [4]:
mandatory = ['Chromosome','Start_Position', 'End_Position','Reference_Allele', 'Tumor_Seq_Allele2']
optional = ['Tumor_Sample_Barcode', 't_depth', 't_ref_count', 't_alt_count', 'n_depth', 'n_ref_count', 'n_alt_count','FILTER']
print(mandatory  + optional)
new = df.loc[:, mandatory  + optional]
new

['Chromosome', 'Start_Position', 'End_Position', 'Reference_Allele', 'Tumor_Seq_Allele2', 'Tumor_Sample_Barcode', 't_depth', 't_ref_count', 't_alt_count', 'n_depth', 'n_ref_count', 'n_alt_count', 'FILTER']

,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,Tumor_Sample_Barcode,t_depth,t_ref_count,t_alt_count,n_depth,n_ref_count,n_alt_count,FILTER
0,1,942752,942752,C,-,MGNS5_post,513,508,5,417,414,3,artifact_in_normal;t_lod
1,1,956853,956853,C,A,MGNS5_post,166,159,7,103,103,0,PASS
2,1,957251,957251,C,G,MGNS5_post,481,466,15,241,241,0,PASS
3,1,963297,963297,G,A,MGNS5_post,238,234,4,290,290,0,t_lod
4,1,973283,973283,A,G,MGNS5_post,380,377,3,343,343,0,t_lod
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24643,MT,12990,12992,AGC,-,DFC1_pre_FFT,4367,4355,12,1544,1540,4,artifact_in_normal;str_contraction
24644,MT,13762,13762,T,G,DFC1_pre_FFT,3525,3466,59,1275,1260,15,artifact_in_normal;base_quality
24645,MT,14808,14808,T,C,DFC1_pre_FFT,4514,4507,7,1841,1841,0,t_lod
24646,MT,14831,14831,G,A,DFC1_pre_FFT,4606,4598,8,1849,1848,1,t_lod
24647,MT,16390,16390,G,A,DFC1_pre_FFT,4843,4828,15,1745,1735,10,artifact_in_normal

In [5]:
path = '/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_pre_annovar.csv' 
new.to_csv(path, sep = '\t', index=False, header=False)

# RUN ANNOVAR

In [6]:
cmd = f'cd /Users/jacobg/CNN/annovar && perl table_annovar.pl {path} --protocol refGene,clinvar_20210123  --operation gx,f humandb/ -buildver hg38 -out {path.replace("_pre", "")} -xref example/gene_fullxref.txt --remove --otherinfo'
os.system(cmd)

NOTICE: the --polish argument is set ON automatically (use --nopolish to change this behavior)
-----------------------------------------------------------------
NOTICE: Processing operation=gx protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene -exonsort -nofirstcodondel /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_pre_annovar.csv humandb/>
NOTICE: Output files are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.variant_function, /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.exonic_variant_function
NOTICE: Reading gene annotation from humandb/hg38_refGene.txt ... Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 1034383 unique variants in 1034383 input lines
NOTICE: Finished analyzing 1000000 query variants
NOTICE: Reading FASTA sequences from humandb/hg38_refGeneMrna.fa ... Done with 56224 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
NOTICE: Variants with invalid input format are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.invalid_input

NOTICE: Running with system command <coding_change.pl  /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.exonic_variant_function.orig humandb//hg38_refGene.txt humandb//hg38_refGeneMrna.fa -alltranscript -out /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.fa -newevf /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.refGene.exonic_variant_function>
WARNING: cannot find annotation for NM_001330761 in the genefile humandb//hg38_refGene.txt or cannot infer the transcription end site
WARNING: cannot find annotation for NM_001349380 in the genefile humandb//hg38_refGene.txt or cannot infer the transcription end site
WARNING: cannot find annotation for NM_001349381 in the genefile humandb//hg38_refGene.txt or cannot infer the transcription end site
WARNING: cannot find annotation for NM_016598 in the genefile humandb//hg38_refGene.txt or cannot infer the transcription end site
Warning: 82 transcripts are flagged as having potential ORF issues (premature stopcodon or lack of stop codon)
NOTICE: The xrefkey is provided in header as <pLi pRec pNull Gene_full_name Function_description Disease_description Tissue_specificity(Uniprot) Expression(egenetics) Expression(GNF/Atlas) P(HI) P(rec) RVIS RVIS_percentile GDI GDI-Phred>
NOTICE: Finished reading 597255 cross references (each with 15 fields) from example/gene_fullxref.txt
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20210123
NOTICE: Finished reading 5 column headers for '-dbtype clinvar_20210123'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20210123 -buildver hg38 -outfile /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_pre_annovar.csv humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20210123 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.hg38_clinvar_20210123_dropped, and output file with other variants is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.hg38_clinvar_20210123_filtered
NOTICE: Processing next batch with 366779 unique variants in 1182467 input lines
NOTICE: Database index loaded. Total number of bins is 75012 and the number of bins to be scanned is 51138
NOTICE: Scanning filter database humandb/hg38_clinvar_20210123.txt...Done
NOTICE: Variants with invalid input format are written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.invalid_input
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.hg38_multianno.txt

0

Some reformatting of the result that we save over the orginal since these files are quite large!

In [7]:
annovar_path='/Users/jacobg/Dropbox/shared_leif/Jacob/WES_2024/somatic/data/mutect2/combined/combined_somatic_mutations_annovar.csv.hg38_multianno.txt'
results = pd.read_csv(annovar_path, sep='\t')
results = results.rename(columns={'Otherinfo1': 'Tumor_Sample_Barcode',
                                  'Otherinfo2': 't_depth',   
                                  'Otherinfo3': 't_ref_count',
                                  'Otherinfo4': 't_alt_count',
                                  'Otherinfo5': 'n_depth',
                                  'Otherinfo6': 'n_ref_count',
                                  'Otherinfo7': 'n_alt_count',
                                  'Otherinfo8': 'FILTER'})
display(results)
results.to_csv(annovar_path, sep='\t', index=False)

/var/folders/4l/15f8r95x5l7ddlpwz4vddgmc0000gp/T/ipykernel_77448/564887713.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv(annovar_path, sep='\t')

,Chr,Start,End,Ref,Alt,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,AAChange.refGene,pLi.refGene,pRec.refGene,pNull.refGene,Gene_full_name.refGene,Function_description.refGene,Disease_description.refGene,Tissue_specificity(Uniprot).refGene,Expression(egenetics).refGene,Expression(GNF/Atlas).refGene,P(HI).refGene,P(rec).refGene,RVIS.refGene,RVIS_percentile.refGene,GDI.refGene,GDI-Phred.refGene,CLNALLELEID,CLNDN,CLNDISDB,CLNREVSTAT,CLNSIG,Tumor_Sample_Barcode,t_depth,t_ref_count,t_alt_count,n_depth,n_ref_count,n_alt_count,FILTER
0,1,942752,942752,C,-,exonic,SAMD11,NaN,frameshift deletion,SAMD11:NM_001385640:exon11:c.1750delC:p.T586Pf...,1.35381157129201e-10,0.18370000637236,0.816299993492259,sterile alpha motif domain containing 11,FUNCTION: May play a role in photoreceptor dev...,.,.,lymphoreticular;ovary;salivary gland;developme...,.,0.10109,.,.,.,835.24604,5.65821,NaN,NaN,NaN,NaN,NaN,MGNS5_post,513,508,5,417,414,3,artifact_in_normal;t_lod
1,1,956853,956853,C,A,intronic,NOC2L,NaN,NaN,NaN,1.33038194561114e-19,0.0025628417280481,0.997437158271952,NOC2 like nucleolar associated transcriptional...,FUNCTION: Acts as an inhibitor of histone acet...,.,.,unclassifiable (Anatomical System);prostate;ep...,.,0.24042,0.13894,0.036678689,56.26916726,783.46189,5.53337,NaN,NaN,NaN,NaN,NaN,MGNS5_post,166,159,7,103,103,0,PASS
2,1,957251,957251,C,G,exonic,NOC2L,NaN,nonsynonymous SNV,NOC2L:NM_015658:exon3:c.G202C:p.E68Q,1.33038194561114e-19,0.0025628417280481,0.997437158271952,NOC2 like nucleolar associated transcriptional...,FUNCTION: Acts as an inhibitor of histone acet...,.,.,unclassifiable (Anatomical System);prostate;ep...,.,0.24042,0.13894,0.036678689,56.26916726,783.46189,5.53337,NaN,NaN,NaN,NaN,NaN,MGNS5_post,481,466,15,241,241,0,PASS
3,1,963297,963297,G,A,intronic,KLHL17,NaN,NaN,NaN,2.51676266070248e-07,0.722913600252338,0.277086148071396,kelch like family member 17,FUNCTION: Substrate-recognition component of s...,.,.,unclassifiable (Anatomical System);cartilage;s...,dorsal root ganglion;superior cervical ganglio...,0.09980,0.09909,-2.653369885,0.754895022,60.97395,1.58809,NaN,NaN,NaN,NaN,NaN,MGNS5_post,238,234,4,290,290,0,t_lod
4,1,973283,973283,A,G,exonic,PLEKHN1,NaN,nonsynonymous SNV,"PLEKHN1:NM_001367552:exon12:c.A1286G:p.E429G,P...",2.01974835522321e-08,0.659994782009553,0.340005197792964,pleckstrin homology domain containing N1,.,.,.,.,.,0.19904,0.09620,0.900159287,89.32531257,709.4528,5.29021,NaN,NaN,NaN,NaN,NaN,MGNS5_post,380,377,3,343,343,0,t_lod
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1182462,MT,12990,12992,AGC,-,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DFC1_pre_FFT,4367,4355,12,1544,1540,4,artifact_in_normal;str_contraction
1182463,MT,13762,13762,T,G,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DFC1_pre_FFT,3525,3466,59,1275,1260,15,artifact_in_normal;base_quality
1182464,MT,14808,14808,T,C,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DFC1_pre_FFT,4514,4507,7,1841,1841,0,t_lod
1182465,MT,14831,14831,G,A,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DFC1_pre_FFT,4606,4598,8,1849,1848,1,t_lod
1182466,MT,16390,16390,G,A,intergenic,NONE;NONE,dist=NONE;dist=NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DFC1_pre_FFT,4843,4828,15,1745,1735,10,artifact_in_normal